version: "2"

plugins:
  shellcheck:
    enabled: true
    checks:
      SC2162:
        enabled: false
      SC2086:
        enabled: false
  csslint:
    enabled: false
  eslint:
    enabled: false

exclude_patterns:
- "conf/"
- "Apache2/"
- "fonts/"
- "*notas*"
