engines:
  shellcheck:
    enabled: true
    checks:
      SC2162:
        enabled: false
      SC2086:
        enabled: false
      SC2033:
        enabled: false
      SC1090:
        enabled: false
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - python
      - bash
  fixme:
    enabled: true
ratings:
  paths:
  - "**.sh"
  - "**.py"
exclude_paths:
- conf/
- Apache2/
- fonts/
- usr/
