plugins:
  shellcheck:
    enabled: true
    checks:
      SC2162:
        enabled: false
      SC2086:
        enabled: false
  csslint:
    enabled: false
  eslint:
    enabled: false

ratings:
  paths:
  - "**.sh"
  - "**.py"
  - "**.md"

exclude_paths:
- "conf/"
- "Apache2/"
- "fonts/"

exclude_patterns:
- "*notas*"
