---
engines:
  csslint:
    enabled: false
  eslint:
    enabled: false
  shellcheck:
    enabled: true
    checks:
      SC2162:
        enabled: false
      SC2086:
        enabled: false
ratings:
  paths:
  - "**.sh"
  - "**.py"
  - "**.md"
exclude_patterns:
- "/conf/*"
- "/Apache2/*"
- "/fonts/*"
