engines:
  shellcheck:
    enabled: true
    checks:
      SC2162:
        enabled: false
      SC2086:
        enabled: false
      SC2033:
        enabled: false
      SC1090:
        enabled: false
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false

exclude_patterns:
- conf/
- Apache2/
- fonts/
- usr/
